# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [13]:
import numpy as np
import itertools


def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size=(dim, dim))
    return matrix


def det(matrix):
    """
    The function calculates the sum of the products
    of permutations.
    """
    pi = (list(itertools.permutations(range(len(matrix)), len(matrix))))
    res = 0
    for p in pi:
        mul = sign(p)
        for i in range(n):
            mul *= matrix[i][p[i]]
        res += mul
    return res


def sign(p):
    """
    The function  reads the sign in front of each
    multiplication group.
    """
    k = 0
    n = len(p)
    for i in range(n):
        for j in range(i + 1, n):
            if p[i] > p[j]:
                k += 1
    return -1 if k % 2 else 1


while True:
    try:
        n = int(input('Input n(>0): '))
        if n <= 0:
            raise Exception('error')
        break
    except Exception as e:
        print(e)
        continue
matrix = random_matrix(n)
print('Matrix:\n', matrix)
print('Result:', (det(matrix)))
print('NumPy\'s reference result:', round(np.linalg.det(matrix)))



Matrix:
 [[6 1 8 6]
 [9 6 1 7]
 [9 7 7 1]
 [0 8 7 4]]
Result: 5706
NumPy's reference result: 5706
